---
- name: Create Container of app
  hosts: all
  vars:
    ansible_python_interpreter: /Users/amitkumar/opt/anaconda3/bin/python3
  tasks:
    - name: web container
      docker_container:
        name: testcalci
        image: amit1197/scientific_calculator
        state: started
        ports:
          - "8081:80"
        tty: true
        detach: true