---
- name: Pull docker image of app
  hosts: all
  vars:
    ansible_python_interpreter: /Users/amitkumar/opt/anaconda3/bin/python3
  tasks:
    - name: Pull app devops image
      docker_image:
        name: amit1197/scientific_calculator
        source: pull